# Generated by Django 3.0.2 on 2020-01-25 18:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('content', models.TextField()),
                ('by_admin', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField(null=True)),
                ('publish_date', models.DateTimeField(null=True)),
                ('is_pablish', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['publish_date'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=250)),
                ('publish_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lake_api.Post')),
            ],
            options={
                'ordering': ['publish_date'],
            },
        ),
    ]
