# Generated by Django 3.0.3 on 2020-02-16 19:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lake_api', '0002_auto_20200216_1939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileupload',
            old_name='owner',
            new_name='post',
        ),
        migrations.AlterField(
            model_name='comment',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 2, 16, 19, 49, 33, 983889, tzinfo=utc)),
        ),
    ]
