# Generated by Django 3.0.4 on 2020-03-22 09:43

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lake_api', '0007_auto_20200315_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='by_admin',
            field=models.BooleanField(default=True, verbose_name='От имени админа'),
        ),
        migrations.AddField(
            model_name='comment',
            name='username',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Имя автора'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='lake_api.Post'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 22, 9, 43, 27, 973373, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='data_file',
            field=models.FileField(upload_to='', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='lake_api.Post', verbose_name='Название поста'),
        ),
        migrations.AlterField(
            model_name='post',
            name='by_admin',
            field=models.BooleanField(default=True, verbose_name='От имени админа'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_publish',
            field=models.BooleanField(default=False, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publish_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='username',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Имя автора'),
        ),
    ]
