# Generated by Django 3.0.4 on 2020-03-26 17:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lake_api', '0009_auto_20200322_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(default='', max_length=50, verbose_name='Слово для фильтрации')),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 26, 17, 34, 14, 771217, tzinfo=utc)),
        ),
    ]
